/**
 * lib/miaa/pays-localization.ts
 * Moteur de localisation par pays pour MIAA+ Expertise
 * Données fiscales, sociales et légales par pays OHADA + Europe
 */

export interface PaysData {
  nom:              string
  devise:           string
  symbole:          string
  cadre_legal:      string
  langue:           string
  tva:              number   // taux TVA principal %
  tva_note?:        string   // ex: "+ CA 5%"
  is:               number   // impôt sur les sociétés %
  cnss_salarial:    number
  cnss_patronal:    number
  irpp_max:         number
  smic_mensuel?:    number   // en devise locale
  notes_fiscales:   string
  notes_sociales:   string
  code_travail:     string
  tribunal:         string
}

export const PAYS_CONFIG: Record<string, PaysData> = {
  'Congo': {
    nom:           'République du Congo',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA (AUDCIF SYSCOHADA Révisé 2017)',
    langue:        'fr',
    tva:           18,
    tva_note:      '+ Centime Additionnel 5% de la TVA',
    is:            30,
    cnss_salarial: 5.04,
    cnss_patronal: 14.36,
    irpp_max:      40,
    smic_mensuel:  90_000,
    notes_fiscales: 'DGI Congo · TVA 18% + CA 5% · IS 30% · Patente annuelle · Acomptes IS trimestriels',
    notes_sociales: 'CNSS Congo · Salarial 5.04% · Patronal 14.36% · Déclaration le 20 du mois',
    code_travail:  'Code du Travail congolais Loi 45-75',
    tribunal:      'Tribunal de Commerce de Brazzaville',
  },
  'RDC': {
    nom:           'République Démocratique du Congo',
    devise:        'CDF',
    symbole:       'FC',
    cadre_legal:   'OHADA (AUDCIF SYSCOHADA Révisé 2017)',
    langue:        'fr',
    tva:           16,
    is:            30,
    cnss_salarial: 5,
    cnss_patronal: 13,
    irpp_max:      40,
    notes_fiscales: 'DGI RDC · TVA 16% · IS 30% · Impôt Professionnel sur les Revenus (IPR)',
    notes_sociales: 'INSS RDC · Salarial 5% · Patronal 13%',
    code_travail:  'Code du Travail RDC Loi n°015-2002',
    tribunal:      'Tribunal de Commerce de Kinshasa',
  },
  'Cameroun': {
    nom:           'République du Cameroun',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA (AUDCIF SYSCOHADA Révisé 2017)',
    langue:        'fr',
    tva:           19.25,
    is:            30,
    cnss_salarial: 2.8,
    cnss_patronal: 11.2,
    irpp_max:      35,
    notes_fiscales: 'DGI Cameroun · TVA 19.25% · IS 30% · CFCE · Acomptes IS',
    notes_sociales: 'CNPS Cameroun · Salarial 2.8% · Patronal 11.2% (AT + vieillesse + AF)',
    code_travail:  'Code du Travail camerounais Loi n°92/007',
    tribunal:      'Tribunal de Commerce de Douala',
  },
  'Gabon': {
    nom:           'République Gabonaise',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA (AUDCIF SYSCOHADA Révisé 2017)',
    langue:        'fr',
    tva:           18,
    is:            30,
    cnss_salarial: 2.5,
    cnss_patronal: 20.1,
    irpp_max:      35,
    notes_fiscales: 'DGI Gabon · TVA 18% · IS 30% · IRCM sur dividendes',
    notes_sociales: 'CNSS Gabon · Salarial 2.5% · Patronal 20.1%',
    code_travail:  'Code du Travail gabonais',
    tribunal:      'Tribunal de Commerce de Libreville',
  },
  'Tchad': {
    nom:           'République du Tchad',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA (AUDCIF SYSCOHADA Révisé 2017)',
    langue:        'fr',
    tva:           18,
    is:            35,
    cnss_salarial: 3.5,
    cnss_patronal: 16.5,
    irpp_max:      40,
    notes_fiscales: 'DGF Tchad · TVA 18% · IS 35%',
    notes_sociales: 'CNPS Tchad · Salarial 3.5% · Patronal 16.5%',
    code_travail:  'Code du Travail tchadien',
    tribunal:      "Tribunal de Commerce de N'Djamena",
  },
  'RCA': {
    nom:           'République Centrafricaine',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA',
    langue:        'fr',
    tva:           19,
    is:            30,
    cnss_salarial: 3,
    cnss_patronal: 14,
    irpp_max:      35,
    notes_fiscales: 'DGTCP RCA · TVA 19% · IS 30%',
    notes_sociales: 'CNSS RCA · Salarial 3% · Patronal 14%',
    code_travail:  'Code du Travail centrafricain',
    tribunal:      'Tribunal de Bangui',
  },
  'Guinée Équatoriale': {
    nom:           'République de Guinée Équatoriale',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA',
    langue:        'fr',
    tva:           15,
    is:            35,
    cnss_salarial: 1,
    cnss_patronal: 21.5,
    irpp_max:      35,
    notes_fiscales: 'DGII GE · TVA 15% · IS 35%',
    notes_sociales: 'INSESO GE · Patronal 21.5%',
    code_travail:  'Code du Travail équatoguinéen',
    tribunal:      'Tribunal de Malabo',
  },
  'Angola': {
    nom:           "République d'Angola",
    devise:        'AOA (Kwanza)',
    symbole:       'Kz',
    cadre_legal:   'Droit angolais',
    langue:        'pt',
    tva:           14,
    is:            25,
    cnss_salarial: 3,
    cnss_patronal: 8,
    irpp_max:      25,
    notes_fiscales: 'AGT Angola · IVA 14% · IRC 25%',
    notes_sociales: 'INSS Angola · Salarial 3% · Patronal 8%',
    code_travail:  'Loi Générale du Travail angolaise',
    tribunal:      'Tribunal de Commerce de Luanda',
  },
  'Mali': {
    nom:           'République du Mali',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA',
    langue:        'fr',
    tva:           18,
    is:            30,
    cnss_salarial: 3.6,
    cnss_patronal: 13.4,
    irpp_max:      40,
    notes_fiscales: 'DGI Mali · TVA 18% · IS 30%',
    notes_sociales: 'INPS Mali · Salarial 3.6% · Patronal 13.4%',
    code_travail:  'Code du Travail malien',
    tribunal:      'Tribunal de Commerce de Bamako',
  },
  'Burkina Faso': {
    nom:           'Burkina Faso',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA',
    langue:        'fr',
    tva:           18,
    is:            27.5,
    cnss_salarial: 5.5,
    cnss_patronal: 16,
    irpp_max:      30,
    notes_fiscales: 'DGI Burkina · TVA 18% · IS 27.5%',
    notes_sociales: 'CNSS Burkina · Salarial 5.5% · Patronal 16%',
    code_travail:  'Code du Travail burkinabè',
    tribunal:      'Tribunal de Commerce de Ouagadougou',
  },
  'Sénégal': {
    nom:           'République du Sénégal',
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA',
    langue:        'fr',
    tva:           18,
    is:            30,
    cnss_salarial: 5.6,
    cnss_patronal: 14,
    irpp_max:      40,
    notes_fiscales: 'DGID Sénégal · TVA 18% · IS 30%',
    notes_sociales: 'IPRES/CSS Sénégal · Salarial 5.6% · Patronal 14%',
    code_travail:  'Code du Travail sénégalais',
    tribunal:      'Tribunal du Commerce de Dakar',
  },
  'Côte d\'Ivoire': {
    nom:           "République de Côte d'Ivoire",
    devise:        'FCFA',
    symbole:       'F',
    cadre_legal:   'OHADA',
    langue:        'fr',
    tva:           18,
    is:            25,
    cnss_salarial: 6.3,
    cnss_patronal: 14.7,
    irpp_max:      36,
    notes_fiscales: 'DGI CI · TVA 18% · IS 25%',
    notes_sociales: 'CNPS CI · Salarial 6.3% · Patronal 14.7%',
    code_travail:  "Code du Travail ivoirien",
    tribunal:      "Tribunal de Commerce d'Abidjan",
  },
  'France': {
    nom:           'République Française',
    devise:        'EUR',
    symbole:       '€',
    cadre_legal:   'Code de Commerce français',
    langue:        'fr',
    tva:           20,
    is:            25,
    cnss_salarial: 22,
    cnss_patronal: 42,
    irpp_max:      45,
    smic_mensuel:  1767,
    notes_fiscales: 'DGFiP · TVA 20% · IS 25% · Acomptes trimestriels',
    notes_sociales: 'URSSAF · Cotisations salariales ~22% · Patronales ~42%',
    code_travail:  'Code du Travail français',
    tribunal:      'Tribunal de Commerce (selon ressort)',
  },
  'Belgique': {
    nom:           'Royaume de Belgique',
    devise:        'EUR',
    symbole:       '€',
    cadre_legal:   'Code de Droit économique belge',
    langue:        'fr',
    tva:           21,
    is:            25,
    cnss_salarial: 13.07,
    cnss_patronal: 25,
    irpp_max:      50,
    notes_fiscales: 'SPF Finances · TVA 21% · ISOC 25%',
    notes_sociales: 'ONSS Belgique · Salarial 13.07% · Patronal 25%',
    code_travail:  'Code du Travail belge',
    tribunal:      'Tribunal de lʼEntreprise',
  },
  'Suisse': {
    nom:           'Confédération Suisse',
    devise:        'CHF',
    symbole:       'CHF',
    cadre_legal:   'Code des Obligations suisse (CO)',
    langue:        'fr',
    tva:           8.1,
    is:            19.7,
    cnss_salarial: 5.3,
    cnss_patronal: 5.3,
    irpp_max:      35,
    notes_fiscales: 'AFC Suisse · TVA 8.1% · IS ~19.7% (fédéral + cantonal)',
    notes_sociales: 'AVS/AI/APG Suisse · Salarial + Patronal 5.3% AVS',
    code_travail:  'Code des Obligations suisse (CO) Art. 319 ss.',
    tribunal:      'Tribunal de Commerce (selon canton)',
  },
}

export const PAYS_LIST = Object.keys(PAYS_CONFIG)

export function getPaysConfig(pays: string): PaysData {
  return PAYS_CONFIG[pays] ?? PAYS_CONFIG['Congo']
}
